language: python
dist: xenial

python:
#  - "3.6"
#  - "3.7"
  - "3.8"
  - "3.9"

install:
  - pip install --upgrade pip
  - pip list
  - pip install importlib-metadata>=4.0.0
  - pip install setuptools>=49.6.0
  - pip install -r requirements.txt
  - pip install -r requirements_ci.yml

# command to run tests
script:
   pytest --cov=deepod/

after_success:
  - coveralls

notifications:
  email:
    recipients:
      - hongzuoxu@126.com
  on_success: never # default: change
  on_failure: always # default: always
